// ============================================================================
// project_context.cpp — Implementation of ProjectContext
// ============================================================================

#include "project_context.h"

namespace ruby::core {

// Out-of-line destructor and anchor
// Note: signals (projectChanged, activeFileChanged, etc.) are generated by moc
} // namespace ruby::core
