// =============================================================================
// embedded_assets.h — GENERATED FILE, DO NOT EDIT BY HAND
// Generated by tools/embed_assets.py
//
// Returns the bytes of any launcher texture/font baked into the binary.
// Matching is by relative path first ("icons/ui_panel.png"), then by bare
// filename ("ui_panel.png"). This is the FIRST source the asset loaders try,
// so icons, fonts and textures always load — even from deb/rpm installs.
// =============================================================================

#pragma once
#include <cstddef>

#ifdef __cplusplus
extern "C" {
#endif

// Returns true and fills *data/*size if the named asset is embedded.
bool embedded_asset(const char* name, const unsigned char** data, size_t* size);

// Convenience: does any embedded asset exist under this path prefix
// (e.g. "fonts/")? Cheap linear scan over a small table.
bool embedded_asset_has_prefix(const char* prefix);

// Decode embedded image bytes (PNG/JPEG/...) into RGBA pixels via stb_image.
// Returns true on success; *out must be freed with asset_image_free().
bool asset_decode_image(const unsigned char* data, size_t size,
                        unsigned char** out, int* w, int* h);
void asset_image_free(unsigned char* px);

#ifdef __cplusplus
}
#endif
