// AUTO-GENERATED — do not edit by hand.
// Regenerate with: tools/extract_lua_api.py --header > src/tools/lua_api_table.h
//
// Source of truth: the Caver::LibFunction tables inside the game's own ARM32 binary.
// Binary: libswordigo.so (v1.4.13 armeabi-v7a)
// Generated: 2026-09-13
//
// Every entry is a namespace.function the engine actually publishes to Lua.
// `mutating` marks calls that change world/UI state, i.e. the candidates a
// timeline action marker may drop at a timestamp.
#pragma once

#include <cstdint>
#include <string_view>

namespace rbsrc {

enum class ApiKind : std::uint8_t {
    NamespaceFn,    // a function in a global table: Camera.Rumble
    ClassCtor,      // class-level constructor: Vector3.New
    InstanceMember  // metatable member via ':': v:x(), v.__add
};

struct ApiFunction {
    std::string_view lua_namespace;
    std::string_view name;
    std::string_view owner_class;   // Caver class that registers it
    uint32_t         address;       // VA in the ARM32 1.4.13 image
    ApiKind          kind;
    bool             mutating;      // sets state -> marker candidate
};

inline constexpr ApiFunction kGameLuaApi[] = {  // 227 entries
    {"AnimationController", "BlendToAnimation", "AnimationControllerComponent", 0x00291a8du, ApiKind::NamespaceFn, true},
    {"AnimationController", "TimeToCompletion", "AnimationControllerComponent", 0x00291b71u, ApiKind::NamespaceFn, false},
    {"Camera", "FocusAtPoint", "CameraController", 0x0036efb5u, ApiKind::NamespaceFn, true},
    {"Camera", "FocusAtShape", "CameraController", 0x0036f029u, ApiKind::NamespaceFn, true},
    {"Camera", "FollowObject", "CameraController", 0x0036f0e9u, ApiKind::NamespaceFn, true},
    {"Camera", "FollowShape", "CameraController", 0x0036f1b5u, ApiKind::NamespaceFn, true},
    {"Camera", "IsObjectVisible", "CameraController", 0x0036f3e9u, ApiKind::NamespaceFn, false},
    {"Camera", "IsPointVisible", "CameraController", 0x0036f345u, ApiKind::NamespaceFn, false},
    {"Camera", "JumpToFocus", "CameraController", 0x0036f275u, ApiKind::NamespaceFn, true},
    {"Camera", "ResetFocus", "CameraController", 0x0036ef4du, ApiKind::NamespaceFn, true},
    {"Camera", "Rumble", "CameraController", 0x0036f2ddu, ApiKind::NamespaceFn, false},
    {"Character", "AddFlag", "GameViewController", 0x0031b511u, ApiKind::NamespaceFn, true},
    {"Character", "AddItem", "GameViewController", 0x0031aa5du, ApiKind::NamespaceFn, true},
    {"Character", "AddQuest", "GameViewController", 0x0031b0f9u, ApiKind::NamespaceFn, true},
    {"Character", "AddQuestText", "GameViewController", 0x0031b345u, ApiKind::NamespaceFn, true},
    {"Character", "AddSceneFlag", "GameViewController", 0x0031b651u, ApiKind::NamespaceFn, true},
    {"Character", "AddSkill", "GameViewController", 0x0031acd9u, ApiKind::NamespaceFn, true},
    {"Character", "HasFlag", "GameViewController", 0x0031b469u, ApiKind::NamespaceFn, false},
    {"Character", "HasItem", "GameViewController", 0x0031a8d5u, ApiKind::NamespaceFn, false},
    {"Character", "HasQuest", "GameViewController", 0x0031aeedu, ApiKind::NamespaceFn, false},
    {"Character", "HasSceneFlag", "GameViewController", 0x0031b5b1u, ApiKind::NamespaceFn, false},
    {"Character", "HasSkill", "GameViewController", 0x0031ac15u, ApiKind::NamespaceFn, false},
    {"Character", "IsQuestCompleted", "GameViewController", 0x0031b049u, ApiKind::NamespaceFn, false},
    {"Character", "IsQuestInProgress", "GameViewController", 0x0031af99u, ApiKind::NamespaceFn, false},
    {"Character", "ItemCount", "GameViewController", 0x0031a999u, ApiKind::NamespaceFn, false},
    {"Character", "NumCoins", "GameViewController", 0x0031adc1u, ApiKind::NamespaceFn, false},
    {"Character", "RegisterTreasure", "GameViewController", 0x0031b6e9u, ApiKind::NamespaceFn, true},
    {"Character", "RegisterTreasureCollection", "GameViewController", 0x0031b775u, ApiKind::NamespaceFn, true},
    {"Character", "RemoveItem", "GameViewController", 0x0031ab45u, ApiKind::NamespaceFn, true},
    {"Character", "SetNumCoins", "GameViewController", 0x0031ae4du, ApiKind::NamespaceFn, true},
    {"Character", "SetQuestCompleted", "GameViewController", 0x0031b295u, ApiKind::NamespaceFn, true},
    {"CharController", "CarriedObject", "CharControllerComponent", 0x002adac1u, ApiKind::NamespaceFn, false},
    {"CharController", "DropObject", "CharControllerComponent", 0x002adb47u, ApiKind::NamespaceFn, true},
    {"CharController", "PickupObject", "CharControllerComponent", 0x002adaf5u, ApiKind::NamespaceFn, true},
    {"CharController", "SetWeaponsHidden", "CharControllerComponent", 0x002adb85u, ApiKind::NamespaceFn, true},
    {"CollectableItem", "IsItemCollected", "CollectableItemComponent", 0x002af175u, ApiKind::NamespaceFn, false},
    {"CollectableItem", "ItemIdentifier", "CollectableItemComponent", 0x002aefcdu, ApiKind::NamespaceFn, false},
    {"CollectableItem", "ItemName", "CollectableItemComponent", 0x002aef61u, ApiKind::NamespaceFn, false},
    {"CollectableItem", "ItemTitle", "CollectableItemComponent", 0x002af0adu, ApiKind::NamespaceFn, false},
    {"CollectableItem", "RequiresPickup", "CollectableItemComponent", 0x002af1a1u, ApiKind::NamespaceFn, false},
    {"CollectableItem", "SetItemIdentifier", "CollectableItemComponent", 0x002af039u, ApiKind::NamespaceFn, true},
    {"CollisionShape", "DisableAll", "CollisionShapeComponent", 0x00290d95u, ApiKind::NamespaceFn, false},
    {"CollisionShape", "IsEnabled", "CollisionShapeComponent", 0x00290d09u, ApiKind::NamespaceFn, false},
    {"CollisionShape", "SetEnabled", "CollisionShapeComponent", 0x00290d4du, ApiKind::NamespaceFn, true},
    {"Damage", "IsActive", "DamageComponent", 0x002afe65u, ApiKind::NamespaceFn, false},
    {"Damage", "SetActive", "DamageComponent", 0x002afe95u, ApiKind::NamespaceFn, true},
    {"DoorController", "Close", "DoorControllerComponent", 0x002d09f9u, ApiKind::NamespaceFn, true},
    {"DoorController", "Open", "DoorControllerComponent", 0x002d09d9u, ApiKind::NamespaceFn, true},
    {"ElevatorController", "GetMode", "ElevatorControllerComponent", 0x002d1431u, ApiKind::NamespaceFn, false},
    {"ElevatorController", "SetMode", "ElevatorControllerComponent", 0x002d14adu, ApiKind::NamespaceFn, true},
    {"Entity", "GetFacingDirection", "EntityComponent", 0x002b129du, ApiKind::NamespaceFn, false},
    {"Entity", "GetPreviousGroundPosition", "EntityComponent", 0x002b1331u, ApiKind::NamespaceFn, false},
    {"Entity", "IsOnGround", "EntityComponent", 0x002b1303u, ApiKind::NamespaceFn, false},
    {"Entity", "SetFacingDirection", "EntityComponent", 0x002b12c7u, ApiKind::NamespaceFn, true},
    {"Entity", "SetPhysicsEnabled", "EntityComponent", 0x002b1399u, ApiKind::NamespaceFn, true},
    {"EntityController", "Acceleration", "EntityControllerComponent", 0x002b29d5u, ApiKind::NamespaceFn, false},
    {"EntityController", "CancelAction", "EntityControllerComponent", 0x002b2b29u, ApiKind::NamespaceFn, true},
    {"EntityController", "DefaultAcceleration", "EntityControllerComponent", 0x002b2a6du, ApiKind::NamespaceFn, false},
    {"EntityController", "DefaultMoveAnimation", "EntityControllerComponent", 0x002b2e93u, ApiKind::NamespaceFn, false},
    {"EntityController", "DefaultMoveSpeed", "EntityControllerComponent", 0x002b2a09u, ApiKind::NamespaceFn, false},
    {"EntityController", "FacingDirection", "EntityControllerComponent", 0x002b27a3u, ApiKind::NamespaceFn, false},
    {"EntityController", "HasRoamBounds", "EntityControllerComponent", 0x002b2c29u, ApiKind::NamespaceFn, false},
    {"EntityController", "IdleTime", "EntityControllerComponent", 0x002b2bf5u, ApiKind::NamespaceFn, false},
    {"EntityController", "IsActionCancelled", "EntityControllerComponent", 0x002b2b49u, ApiKind::NamespaceFn, false},
    {"EntityController", "IsIdle", "EntityControllerComponent", 0x002b2b75u, ApiKind::NamespaceFn, false},
    {"EntityController", "MoveDirection", "EntityControllerComponent", 0x002b27cfu, ApiKind::NamespaceFn, false},
    {"EntityController", "MoveSpeed", "EntityControllerComponent", 0x002b29a1u, ApiKind::NamespaceFn, false},
    {"EntityController", "MovementBehavior", "EntityControllerComponent", 0x002b2cb9u, ApiKind::NamespaceFn, false},
    {"EntityController", "PerformAction", "EntityControllerComponent", 0x002b2aa1u, ApiKind::NamespaceFn, true},
    {"EntityController", "RoamBounds", "EntityControllerComponent", 0x002b2c59u, ApiKind::NamespaceFn, false},
    {"EntityController", "SetAcceleration", "EntityControllerComponent", 0x002b294du, ApiKind::NamespaceFn, true},
    {"EntityController", "SetDefaultMoveSpeed", "EntityControllerComponent", 0x002b2a3du, ApiKind::NamespaceFn, true},
    {"EntityController", "SetFacingDirection", "EntityControllerComponent", 0x002b27f9u, ApiKind::NamespaceFn, true},
    {"EntityController", "SetMoveAnimation", "EntityControllerComponent", 0x002b2ed5u, ApiKind::NamespaceFn, true},
    {"EntityController", "SetMoveDirection", "EntityControllerComponent", 0x002b2879u, ApiKind::NamespaceFn, true},
    {"EntityController", "SetMoveSpeed", "EntityControllerComponent", 0x002b28f9u, ApiKind::NamespaceFn, true},
    {"EntityController", "SetMovementBehavior", "EntityControllerComponent", 0x002b2d2du, ApiKind::NamespaceFn, true},
    {"EntityController", "SetTarget", "EntityControllerComponent", 0x002b2dc5u, ApiKind::NamespaceFn, true},
    {"EntityController", "StartSwing", "EntityControllerComponent", 0x002b2e35u, ApiKind::NamespaceFn, false},
    {"EntityController", "Target", "EntityControllerComponent", 0x002b2d99u, ApiKind::NamespaceFn, false},
    {"Game", "CurrentLevelName", "GameViewController", 0x0031c0e5u, ApiKind::NamespaceFn, false},
    {"Game", "DefaultMusicName", "GameViewController", 0x0031c21du, ApiKind::NamespaceFn, false},
    {"Game", "EnterPortal", "GameViewController", 0x0031c18du, ApiKind::NamespaceFn, true},
    {"Game", "FadeIn", "GameViewController", 0x0031be49u, ApiKind::NamespaceFn, true},
    {"Game", "FadeOut", "GameViewController", 0x0031bdb1u, ApiKind::NamespaceFn, true},
    {"Game", "Flash", "GameViewController", 0x0031c061u, ApiKind::NamespaceFn, true},
    {"Game", "GotoCredits", "GameViewController", 0x0031c3d5u, ApiKind::NamespaceFn, true},
    {"Game", "HideItemInfoPopup", "GameViewController", 0x0031bba1u, ApiKind::NamespaceFn, true},
    {"Game", "IncCounter", "GameViewController", 0x0031c321u, ApiKind::NamespaceFn, true},
    {"Game", "IsItemUnique", "GameViewController", 0x0031b9f5u, ApiKind::NamespaceFn, false},
    {"Game", "SetCinematicMode", "GameViewController", 0x0031bee1u, ApiKind::NamespaceFn, true},
    {"Game", "SetDefaultMusicName", "GameViewController", 0x0031c299u, ApiKind::NamespaceFn, true},
    {"Game", "ShowItemBuyPopup", "GameViewController", 0x0031bc09u, ApiKind::NamespaceFn, true},
    {"Game", "ShowItemInfoPopup", "GameViewController", 0x0031bad1u, ApiKind::NamespaceFn, true},
    {"Game", "ShowNotification", "GameViewController", 0x0031b801u, ApiKind::NamespaceFn, true},
    {"Game", "TitleForItem", "GameViewController", 0x0031b8f1u, ApiKind::NamespaceFn, false},
    {"Health", "CurrentHealth", "HealthComponent", 0x002b4d85u, ApiKind::NamespaceFn, false},
    {"Health", "CurrentPercent", "HealthComponent", 0x002b4e11u, ApiKind::NamespaceFn, false},
    {"Health", "HasTakenDamage", "HealthComponent", 0x002b4e61u, ApiKind::NamespaceFn, false},
    {"Health", "MaxHealth", "HealthComponent", 0x002b4de7u, ApiKind::NamespaceFn, false},
    {"Health", "MaxMana", "HealthComponent", 0x002b4effu, ApiKind::NamespaceFn, false},
    {"Health", "SetCurrentHealth", "HealthComponent", 0x002b4dadu, ApiKind::NamespaceFn, true},
    {"Health", "SetCurrentMana", "HealthComponent", 0x002b4ecbu, ApiKind::NamespaceFn, true},
    {"Health", "SetImmunityTime", "HealthComponent", 0x002b4e8bu, ApiKind::NamespaceFn, true},
    {"ItemDrop", "AllItemsCollected", "ItemDropComponent", 0x002b8747u, ApiKind::NamespaceFn, false},
    {"ItemDrop", "ItemIdentifier", "ItemDropComponent", 0x002b879du, ApiKind::NamespaceFn, false},
    {"ItemDrop", "NumItems", "ItemDropComponent", 0x002b8775u, ApiKind::NamespaceFn, false},
    {"ItemDrop", "SetItemIdentifier", "ItemDropComponent", 0x002b87e5u, ApiKind::NamespaceFn, true},
    {"ItemDrop", "Trigger", "ItemDropComponent", 0x002b8727u, ApiKind::NamespaceFn, true},
    {"KeyframeAnimation", "Duration", "KeyframeAnimationComponent", 0x00293849u, ApiKind::NamespaceFn, false},
    {"KeyframeAnimation", "SetCurrentTime", "KeyframeAnimationComponent", 0x002937cfu, ApiKind::NamespaceFn, true},
    {"KeyframeAnimation", "SetReversed", "KeyframeAnimationComponent", 0x00293789u, ApiKind::NamespaceFn, true},
    {"KeyframeAnimation", "SetRunning", "KeyframeAnimationComponent", 0x00293743u, ApiKind::NamespaceFn, true},
    {"KeyframeAnimation", "TimeToCompletion", "KeyframeAnimationComponent", 0x00293919u, ApiKind::NamespaceFn, false},
    {"KeyframeAnimation", "TimeToFrame", "KeyframeAnimationComponent", 0x002938adu, ApiKind::NamespaceFn, false},
    {"Light", "OverlayIntensity", "LightComponent", 0x0029464du, ApiKind::NamespaceFn, false},
    {"Light", "SetOverlayIntensity", "LightComponent", 0x002946ddu, ApiKind::NamespaceFn, true},
    {"Math", "Abs", "ProgramMath", 0x003a1a23u, ApiKind::NamespaceFn, false},
    {"Math", "RandomFloat", "ProgramMath", 0x003a19a1u, ApiKind::NamespaceFn, false},
    {"Math", "RandomInt", "ProgramMath", 0x003a19e7u, ApiKind::NamespaceFn, false},
    {"Math", "Sin", "ProgramMath", 0x003a1a41u, ApiKind::NamespaceFn, false},
    {"ModelTransformController", "SetOrigin", "ModelTransformControllerComponent", 0x0029688fu, ApiKind::NamespaceFn, true},
    {"ModelTransformController", "SetRotationAngle", "ModelTransformControllerComponent", 0x00296909u, ApiKind::NamespaceFn, true},
    {"ModelTransformController", "SetRotationAxis", "ModelTransformControllerComponent", 0x002968d5u, ApiKind::NamespaceFn, true},
    {"ModelTransformController", "SetRotationSpeed", "ModelTransformControllerComponent", 0x00296959u, ApiKind::NamespaceFn, true},
    {"MusicPlayer", "FadeIn", "MusicPlayer", 0x00381729u, ApiKind::NamespaceFn, true},
    {"MusicPlayer", "FadeOut", "MusicPlayer", 0x00381695u, ApiKind::NamespaceFn, true},
    {"MusicPlayer", "PlayMusic", "MusicPlayer", 0x003815f1u, ApiKind::NamespaceFn, true},
    {"ObjectLinkController", "LinkToBone", "ObjectLinkControllerComponent", 0x00297be1u, ApiKind::NamespaceFn, true},
    {"ObjectLinkController", "LinkToObject", "ObjectLinkControllerComponent", 0x00297b75u, ApiKind::NamespaceFn, true},
    {"ObjectLinkController", "SetLocalOffset", "ObjectLinkControllerComponent", 0x00297b05u, ApiKind::NamespaceFn, true},
    {"ObjectLinkController", "SetWorldOffset", "ObjectLinkControllerComponent", 0x00297b3du, ApiKind::NamespaceFn, true},
    {"OverlayText", "SetText", "OverlayTextComponent", 0x00299805u, ApiKind::NamespaceFn, true},
    {"ParticleEmitter", "ParameterAtIndex", "ParticleEmitterComponent", 0x002cd189u, ApiKind::NamespaceFn, false},
    {"ParticleEmitter", "SetColor", "ParticleEmitterComponent", 0x002cd0bdu, ApiKind::NamespaceFn, true},
    {"ParticleEmitter", "SetOriginOffset", "ParticleEmitterComponent", 0x002cd011u, ApiKind::NamespaceFn, true},
    {"ParticleEmitter", "SetParameterAtIndex", "ParticleEmitterComponent", 0x002cd23du, ApiKind::NamespaceFn, true},
    {"ParticleEmitter", "Test", "ParticleEmitterComponent", 0x002ccff9u, ApiKind::NamespaceFn, false},
    {"PhysicsObject", "IsEnabled", "PhysicsObjectComponent", 0x002baa01u, ApiKind::NamespaceFn, false},
    {"PhysicsObject", "OriginalPosition", "PhysicsObjectComponent", 0x002bab3du, ApiKind::NamespaceFn, false},
    {"PhysicsObject", "SetDecelerationForce", "PhysicsObjectComponent", 0x002bab09u, ApiKind::NamespaceFn, true},
    {"PhysicsObject", "SetEnabled", "PhysicsObjectComponent", 0x002baa33u, ApiKind::NamespaceFn, true},
    {"PhysicsObject", "SetGravityDirection", "PhysicsObjectComponent", 0x002baa65u, ApiKind::NamespaceFn, true},
    {"PhysicsObject", "SetGravityMagnitude", "PhysicsObjectComponent", 0x002baac9u, ApiKind::NamespaceFn, true},
    {"Portal", "Activate", "PortalComponent", 0x0029a465u, ApiKind::NamespaceFn, true},
    {"Portal", "Deactivate", "PortalComponent", 0x0029a483u, ApiKind::NamespaceFn, true},
    {"Program", "Execute", "ProgramComponent", 0x0029ae6fu, ApiKind::NamespaceFn, false},
    {"Program", "IsRunning", "ProgramComponent", 0x0029aea7u, ApiKind::NamespaceFn, false},
    {"Program", "Print", "ProgramState", 0x003a0e05u, ApiKind::NamespaceFn, false},
    {"Program", "SetKeepActive", "ProgramState", 0x003a0e09u, ApiKind::NamespaceFn, true},
    {"Program", "Wait", "ProgramState", 0x003a0dd9u, ApiKind::NamespaceFn, false},
    {"Properties", "GetProperty", "PropertiesComponent", 0x0029b4b9u, ApiKind::NamespaceFn, false},
    {"Properties", "SetProperty", "PropertiesComponent", 0x0029b435u, ApiKind::NamespaceFn, true},
    {"Rectangle", ":bottom", "ProgramMath", 0x003a17fdu, ApiKind::InstanceMember, false},
    {"Rectangle", ":left", "ProgramMath", 0x003a17e1u, ApiKind::InstanceMember, false},
    {"Rectangle", ":right", "ProgramMath", 0x003a1819u, ApiKind::InstanceMember, false},
    {"Rectangle", ":toString", "ProgramMath", 0x003a186du, ApiKind::InstanceMember, false},
    {"Rectangle", ":top", "ProgramMath", 0x003a1843u, ApiKind::InstanceMember, false},
    {"Rectangle", "New", "ProgramMath", 0x003a174du, ApiKind::ClassCtor, false},
    {"Scene", "AddObject", "Scene", 0x00376e11u, ApiKind::NamespaceFn, true},
    {"Scene", "CreateObject", "Scene", 0x00376cd1u, ApiKind::NamespaceFn, false},
    {"Scene", "Find", "Scene", 0x00376c29u, ApiKind::NamespaceFn, false},
    {"Scene", "OverrideLights", "Scene", 0x00376fbdu, ApiKind::NamespaceFn, true},
    {"Scene", "ResetLights", "Scene", 0x00377059u, ApiKind::NamespaceFn, true},
    {"Scene", "SetGroupHidden", "Scene", 0x00376f19u, ApiKind::NamespaceFn, true},
    {"Scene", "SetPaused", "Scene", 0x00376e9du, ApiKind::NamespaceFn, true},
    {"SceneObject", "__eq", "SceneObjectLib", 0x0037ca55u, ApiKind::NamespaceFn, false},
    {"SceneObject", "__gc", "SceneObjectLib", 0x0037ca3du, ApiKind::NamespaceFn, false},
    {"SceneObject", "__index", "SceneObjectLib", 0x0037ca81u, ApiKind::NamespaceFn, false},
    {"SceneObject", "__newindex", "SceneObjectLib", 0x0037cb13u, ApiKind::NamespaceFn, false},
    {"SceneObject", "activate", "SceneObjectLib", 0x0037ccc7u, ApiKind::NamespaceFn, false},
    {"SceneObject", "addComponent", "SceneObjectLib", 0x0037cd55u, ApiKind::NamespaceFn, false},
    {"SceneObject", "clone", "SceneObjectLib", 0x0037cdcdu, ApiKind::NamespaceFn, false},
    {"SceneObject", "depth", "SceneObjectLib", 0x0037cf95u, ApiKind::NamespaceFn, false},
    {"SceneObject", "destroy", "SceneObjectLib", 0x0037cc85u, ApiKind::NamespaceFn, false},
    {"SceneObject", "identifier", "SceneObjectLib", 0x0037cba1u, ApiKind::NamespaceFn, false},
    {"SceneObject", "isAlive", "SceneObjectLib", 0x0037cc57u, ApiKind::NamespaceFn, false},
    {"SceneObject", "isHidden", "SceneObjectLib", 0x0037cc09u, ApiKind::NamespaceFn, false},
    {"SceneObject", "position", "SceneObjectLib", 0x0037ceb9u, ApiKind::NamespaceFn, false},
    {"SceneObject", "position2", "SceneObjectLib", 0x0037cdf5u, ApiKind::NamespaceFn, false},
    {"SceneObject", "rotation", "SceneObjectLib", 0x0037cfedu, ApiKind::NamespaceFn, false},
    {"SceneObject", "scaling", "SceneObjectLib", 0x0037d125u, ApiKind::NamespaceFn, false},
    {"SceneObject", "setAlwaysActive", "SceneObjectLib", 0x0037cc9fu, ApiKind::NamespaceFn, false},
    {"SceneObject", "setDepth", "SceneObjectLib", 0x0037cfc5u, ApiKind::NamespaceFn, false},
    {"SceneObject", "setHidden", "SceneObjectLib", 0x0037cc2fu, ApiKind::NamespaceFn, false},
    {"SceneObject", "setParentObject", "SceneObjectLib", 0x0037cce1u, ApiKind::NamespaceFn, false},
    {"SceneObject", "setPosition", "SceneObjectLib", 0x0037cf29u, ApiKind::NamespaceFn, false},
    {"SceneObject", "setPosition2", "SceneObjectLib", 0x0037ce5du, ApiKind::NamespaceFn, false},
    {"SceneObject", "setRotation", "SceneObjectLib", 0x0037d029u, ApiKind::NamespaceFn, false},
    {"SceneObject", "setScaling", "SceneObjectLib", 0x0037d14fu, ApiKind::NamespaceFn, false},
    {"SceneObject", "setVelocity", "SceneObjectLib", 0x0037d0cdu, ApiKind::NamespaceFn, false},
    {"SceneObject", "velocity", "SceneObjectLib", 0x0037d065u, ApiKind::NamespaceFn, false},
    {"Skill", "BeginCasting", "SkillComponent", 0x002c1985u, ApiKind::NamespaceFn, true},
    {"Skill", "CancelCasting", "SkillComponent", 0x002c1a6fu, ApiKind::NamespaceFn, true},
    {"Skill", "FinishCasting", "SkillComponent", 0x002c1a51u, ApiKind::NamespaceFn, true},
    {"Skill", "Origin", "SkillComponent", 0x002c1a8du, ApiKind::NamespaceFn, false},
    {"SnappingMonsterController", "Attack", "SnappingMonsterControllerComponent", 0x002c8a19u, ApiKind::NamespaceFn, true},
    {"SoundLibrary", "PlayEffect", "SoundLibrary", 0x003831e1u, ApiKind::NamespaceFn, true},
    {"Spell", "CastPoint", "SpellComponent", 0x002c20d5u, ApiKind::NamespaceFn, true},
    {"Spell", "CasterObject", "SpellComponent", 0x002c206du, ApiKind::NamespaceFn, true},
    {"TextBubble", "IsTextFinished", "TextBubbleComponent", 0x0029f3f1u, ApiKind::NamespaceFn, false},
    {"TextBubble", "SetTouchHandlingEnabled", "TextBubbleComponent", 0x0029f41fu, ApiKind::NamespaceFn, true},
    {"TextBubble", "ShowText", "TextBubbleComponent", 0x0029f34du, ApiKind::NamespaceFn, true},
    {"Touchable", "SetTouchRadius", "TouchableComponent", 0x0029ffa1u, ApiKind::NamespaceFn, true},
    {"TransformController", "RotateBy", "TransformControllerComponent", 0x002a09fdu, ApiKind::NamespaceFn, true},
    {"TransformController", "RotateTo", "TransformControllerComponent", 0x002a0afdu, ApiKind::NamespaceFn, true},
    {"TransformController", "ScaleBy", "TransformControllerComponent", 0x002a0ab7u, ApiKind::NamespaceFn, true},
    {"TransformController", "ScaleTo", "TransformControllerComponent", 0x002a0bb3u, ApiKind::NamespaceFn, true},
    {"TransformController", "SetOrigin", "TransformControllerComponent", 0x002a09c5u, ApiKind::NamespaceFn, true},
    {"TransformController", "TranslateBy", "TransformControllerComponent", 0x002a0a71u, ApiKind::NamespaceFn, true},
    {"TransformController", "TranslateTo", "TransformControllerComponent", 0x002a0b6du, ApiKind::NamespaceFn, true},
    {"Vector3", ":__add", "ProgramMath", 0x003a1309u, ApiKind::InstanceMember, false},
    {"Vector3", ":__mul", "ProgramMath", 0x003a1401u, ApiKind::InstanceMember, false},
    {"Vector3", ":__sub", "ProgramMath", 0x003a1385u, ApiKind::InstanceMember, false},
    {"Vector3", ":angle", "ProgramMath", 0x003a1475u, ApiKind::InstanceMember, false},
    {"Vector3", ":cross", "ProgramMath", 0x003a1571u, ApiKind::InstanceMember, false},
    {"Vector3", ":distance", "ProgramMath", 0x003a1513u, ApiKind::InstanceMember, false},
    {"Vector3", ":dot", "ProgramMath", 0x003a1541u, ApiKind::InstanceMember, false},
    {"Vector3", ":length", "ProgramMath", 0x003a14d9u, ApiKind::InstanceMember, false},
    {"Vector3", ":normalized", "ProgramMath", 0x003a15d5u, ApiKind::InstanceMember, false},
    {"Vector3", ":toString", "ProgramMath", 0x003a1621u, ApiKind::InstanceMember, false},
    {"Vector3", ":toVector2", "ProgramMath", 0x003a12b9u, ApiKind::InstanceMember, false},
    {"Vector3", ":x", "ProgramMath", 0x003a1265u, ApiKind::InstanceMember, false},
    {"Vector3", ":y", "ProgramMath", 0x003a1281u, ApiKind::InstanceMember, false},
    {"Vector3", ":z", "ProgramMath", 0x003a129du, ApiKind::InstanceMember, false},
    {"Vector3", "FromAngle", "ProgramMath", 0x003a11f9u, ApiKind::ClassCtor, false},
    {"Vector3", "New", "ProgramMath", 0x003a118du, ApiKind::ClassCtor, false},
};

inline constexpr std::size_t kGameLuaApiCount = sizeof(kGameLuaApi) / sizeof(kGameLuaApi[0]);

} // namespace rbsrc
